<?php

/**
 * @file
 * Contains advanced_cors.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function advanced_cors_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the advanced_cors module.
    case 'help.page.advanced_cors':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Advanced CORS settings') . '</p>';
      return $output;

    default:
  }
}
