advanced_cors.route_config.*:
  type: config_entity
  label: 'Route configuration config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    weight:
      type: integer
      label: 'Weight'
    status:
      type: boolean
      label: 'Status'
    patterns:
      type: string
      label: 'Patterns'
    allowed_headers:
      type: string
      label: 'Allowed headers'
    allowed_methods:
      type: string
      label: 'Allowed methods'
    allowed_origins:
      type: string
      label: 'Allowed origins'
    exposed_headers:
      type: string
      label: 'Exposed headers'
    max_age:
      type: string
      label: 'Max age'
    supports_credentials:
      type: string
      label: 'Supports credentials'
